import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
        {/* Fixed back button bottom left */}
        <a
          href="/"
          className="fixed left-6 bottom-6 z-50 bg-white/90 border border-gray-300 rounded-full shadow-lg p-3 flex items-center justify-center hover:bg-blue-100 transition-colors"
          aria-label="Geri Dön"
        >
          <svg width="28" height="28" viewBox="0 0 24 24" fill="none" stroke="#2563eb" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round" className="">
            <path d="M15 18l-6-6 6-6" />
          </svg>
        </a>
      </body>
    </html>
  );
}
